// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiBj7DYpsxwKu5-2lG-1DhTSWhy0X1m_E',
    appId: '1:457284911122:web:67e792cb7ca2f2f46118cb',
    messagingSenderId: '457284911122',
    projectId: 'appmusicaaa',
    authDomain: 'appmusicaaa.firebaseapp.com',
    storageBucket: 'appmusicaaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2EZo4beWSeOAEkgXyNdjfjS09Su74BdU',
    appId: '1:457284911122:android:fe65ac4f927de99b6118cb',
    messagingSenderId: '457284911122',
    projectId: 'appmusicaaa',
    storageBucket: 'appmusicaaa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiBj7DYpsxwKu5-2lG-1DhTSWhy0X1m_E',
    appId: '1:457284911122:web:c895de22d40ef6026118cb',
    messagingSenderId: '457284911122',
    projectId: 'appmusicaaa',
    authDomain: 'appmusicaaa.firebaseapp.com',
    storageBucket: 'appmusicaaa.firebasestorage.app',
  );

}